FROM node:9.5.0-alpine

# set working directory
RUN mkdir -p /usr/src/rethink-web
WORKDIR /usr/src/rethink-web

# add `/usr/src/rethink-web/node_modules/.bin` to $PATH
ENV PATH /usr/src/rethink-web/node_modules/.bin:$PATH

# install and cache rethink-web dependencies
ADD package.json /usr/src/rethink-web/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.1 -g --silent

# start app
CMD ["npm", "start"]