version: '3.4'

services:

  rethink-frontend:
    container_name: rethink-frontend
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '.:/usr/src/rethink-web'
      - '/usr/src/rethink-web/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true